### PR TITLE
Create it.po

### PR DESCRIPTION
**Pull request by airon90**
Added Italian translation

### CODE REVIEW

**Comment by airon90** [comment]
Why didn't you merge my edits?

**Comment by pablo-s** [comment]
Hi @airon90 ! I would love to have your changes. But I started a merge review and I made some suggestions that were never accepted. Also, I sent you a message but it was never replied.
Now that I see that you are interested, I reopen the merge request again.

**Comment by airon90** [comment]
> But I started a merge review and I made some suggestions that were never accepted. Also, I sent you a message but it was never replied

I didn't see nor received a notification about anything of these. Help me to check where these comments/messages are :)

**Comment by pablo-s** [comment]
> > But I started a merge review and I made some suggestions that were never accepted. Also, I sent you a message but it was never replied
> 
> I didn't see nor received a notification about anything of these. Help me to check where these comments/messages are :)

Sure! They are in this pull request. Just read all comments and you will see them.

**Comment by airon90** [comment]
Screenshot_2022-08-08-10-29-40-321_org mozilla fenix

I am sorry but I don't see anything 😅 can you please repost your comments?

**Comment by pablo-s** [comment]
> I am sorry but I don't see anything 😅 can you please repost your comments?

Let's try this way: https://github.com/pablo-s/passes/pull/12#pullrequestreview-974282062

**Comment by airon90** [comment]
> Let's try this way: https://github.com/pablo-s/passes/pull/12#pullrequestreview-974282062

It doesn't do anything. Can you please write here your comments? :)

**Comment by airon90** [comment]
If those lines can be added later that's fine. I am working right now so I will male the changes later/tomorrow ;)

**Pull request merged**
